### ISSUE TITLE
Improve itinerary selection

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#11]
Currently the itinerary selection is very confusing. The logic must be slightly different. 

When you come to the screen you see the different options how to get to your appointment. In our example data it will be three different routes: Train, taxi and plane. There won't be a Choose button. Only when you click on one of those routes, the transport schedule for that route will be opened. Then we need to add the choose button to every transport schedule option and remove the radio button. 

When the user selects a transport schedule, all other options will be hidden and the user can see, what he selected. We need a possibility to change that selection though (a button? Or a hover event showing the user that he can change his selection by clicking?).

![screen shot 2016-06-18 at 10 38 58](https://cloud.githubusercontent.com/assets/5637811/16169937/edfeb870-3540-11e6-9d38-729e31e2d619.png)

**Comment by davidtran** [comment]
I think we can change "Choose" to "Select schedule" and when click on that button we show the schedule options.

**Comment by swapzone** [comment]
Sounds good to me!

**Comment by davidtran** [comment]
![screen shot 2016-06-22 at 7 21 41 ch](https://cloud.githubusercontent.com/assets/1154740/16266346/95a79b6c-38ae-11e6-94e9-309fc4ae2b23.png)


Hey Sascha, I found that it's confusing when we use "Select alternative" because for example, the car route doesn't have any alternatives, so we have to show "Choose" button instead of "Select alternative".

I think it's confusing.

The image above is my idea:
We still use the "Choose" button but we show the timing for that trip. If user is fine with that timing, he clicks "Choose" anyway, it's big button so user won't miss it. 

If user want another timing, he click on show alternative.

How do you think? if you don't like it, I will change it back.

**Comment by swapzone** [comment]
Hey Nam, this is a great solution, let's go for it!

**Comment by davidtran** [comment]
Done

**Comment by swapzone** [comment]
Cool! Works as expected.
