### ISSUE TITLE
Optimize static files serving

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#221]
Hi @vankhoa011 ,

There are few things I want to optimize on our server:
- Improve caching for js, css and image files by etag, cache time
- Turn on gzip on nginx.
- Install google pagespeed for nginx

Let's finish these issues for we move our frontend to CDN.

@GrosR

**Comment by vankhoa011** [comment]
Hi @davidtran 

1. Improve caching for js, css and image files by etag, cache time

How do you think we didn't config caching for JS, CSS. Because when you change the code, the user will not load the new changed because the browser will load from cache. 
So I think it is good if we configure `no-cache` 

2. Turn on gzip on nginx. 
Yes, I will turn on Nginx caching.

3. Install google pagespeed for nginx.
CDN have same features with google pagespeed. So I think I will move it to CDN. 

So how do you think about that ?

**Comment by davidtran** [comment]
Don't worry about the caching issue of caching, the assets build tool adds a hash in file name of generated files and that hash is changed every time we build new assets
