### ISSUE TITLE
Recalculate trips after user change departure location

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#45]
I changed the "departing from" location and the control works fine. However, if the starting point is changing, the whole trip options must be recalculated. 
Currently, nothing happens. 
I suggest to throw a dialog asking, if the user is sure, that he want´s to change the departure location and recalculate the whole itinerary sequence. 
If the users cancels, we should keep the departure location from BEFORE the change - if the users confirms the change, we must recalculate either the itinerary for this appointment and evtl. the whole itinerary sequence of all appointments, in case the Start/End-time of the recalculated itnerary conflicts with other apppointment itineraries.

**Comment by davidtran** [comment]
It's actually recalculate the trips. but since we are using mock data, you can't see changes.

I will implement the dialog in this ticket.

**Comment by davidtran** [comment]
Because each trip can depend on the other trips. If user changes anything on the appointment, it would recalculate the whole trip. I found that it would be easier for the frontend. I already implement it, so I would show the message when user click "Save" button on the dialog. How do you think ? We already discussed about this stuff on Skype.

**Comment by GrosR** [comment]
yes, that is the intended behavior
